<header class="h-24 sm:h-28 sticky top-0 z-50">
    <div class="bg-opacity-60 bg-primary_bg-NORMAL duration-500 false-header h-24 origin-top sticky top-0 transform transition z-50 sm:h-28">
        <div data-empty-placeholder></div>
    </div>
    <div class="-mt-28 container duration-500 h-24 lg:top-2 md:top-0 mossco-header mx-auto px-0 sticky top-1 transform transition z-50"> 
        <nav class="flex flex-wrap items-center justify-between p-4 sm:py-5 md:px-4 lg:py-0"> <a href="/"><img src="<?php echo get_template_directory_uri(); ?>/assets/images/logo/logo-white-teal.svg" class="duration-500 h-9 ml-4 mossco-logo mr-auto scale-125 transform transition lg:h-9"></a>
            <button class="hamburger-menu hover:text-white py-2 rounded text-current md:mr-5 lg:hidden" data-name="nav-toggler" data-pg-ia='{"l":[{"name":"NabMenuToggler","trg":"click","a":{"l":[{"t":"^nav|[data-name=nav-menu]","l":[{"t":"set","p":0,"d":0,"l":{"class.remove":"hidden"}}]},{"t":"#gt# span:nth-of-type(1)","l":[{"t":"tween","p":0,"d":0.2,"l":{"rotationZ":45,"yPercent":300}}]},{"t":"#gt# span:nth-of-type(2)","l":[{"t":"tween","p":0,"d":0.2,"l":{"autoAlpha":0}}]},{"t":"#gt# span:nth-of-type(3)","l":[{"t":"tween","p":0,"d":0.2,"l":{"rotationZ":-45,"yPercent":-400}}]}]},"pdef":"true","trev":"true"}]}' data-pg-ia-apply="$nav [data-name=nav-toggler]"><span class="bg-primary-NORMAL block h-1 hover:bg-primary-LIGHT my-2 rounded ml-auto w-10 sm:w-12"></span><span class="bg-white block h-1 ml-auto my-2.5 rounded w-6 sm:w-8"></span><span class="bg-primary-NORMAL block h-1 hover: my-2.5 rounded ml-auto w-10 sm:w-12"></span>
            </button>
            <a href="#" class="bg-primary-NORMAL font-light hover:bg-primary-700 inline-block nav-btn-tablet-mobile px-5 py-2 rounded text-current text-primary-500 uppercase sm:hidden md:inline-block lg:hidden"><?php _e( 'Book a Table', 'mossco_hc' ); ?></a>
            <div class="bg-opacity-90 bg-primary_bg-NORMAL hidden lg:bg-opacity-0 lg:flex lg:max-w-full lg:space-x-4 lg:space-y-0 lg:text-left lg:w-auto md:max-w-md md:mr-auto mx-auto px-4 py-8 rounded space-y-2 text-center w-full" data-name="nav-menu"> 
                <div class="flex flex-col text-gray-50 lg:flex-row lg:text-sm"> <a href="#home-our-brand" class="font-light hover:text-primary-LIGHT px-0 py-2 uppercase lg:px-4"><?php _e( 'Our Story', 'mossco_hc' ); ?></a> <a href="#home-menus" class="font-light hover:text-primary-LIGHT px-0 py-2 uppercase lg:px-4"><?php _e( 'Menus', 'mossco_hc' ); ?></a> <a href="#home-bar" class="font-light hover:text-primary-LIGHT px-0 py-2 uppercase lg:px-4"><?php _e( 'Bar &#38; Restaurant', 'mossco_hc' ); ?></a><a href="#home-gallery" class="font-light hover:text-primary-LIGHT px-0 py-2 uppercase lg:px-4"><?php _e( 'Gallery', 'mossco_hc' ); ?></a> <a href="#details-map" class="font-light hover:text-primary-LIGHT px-0 py-2 uppercase lg:px-4"><?php _e( 'Location', 'mossco_hc' ); ?></a> <a href="#home-newsletter" class="font-light hover:text-primary-LIGHT px-0 py-2 uppercase lg:px-4"><?php _e( 'Newsletter', 'mossco_hc' ); ?></a>
                </div>                 <a href="#" class="active:bg-primary-DARK bg-primary-NORMAL duration-300 ease-out font-light hover:bg-primary-LIGHT hover:ring hover:ring-primary-DARK inline-block px-5 py-2 rounded text-white transition uppercase"><?php _e( 'Book a Table', 'mossco_hc' ); ?></a> 
            </div>             
        </nav>         
    </div>
</header>